'use client';
import {useState,type FormEvent} from 'react';
import {api,mutate} from '@/lib/api';
import type {Direction} from '@/lib/types';
import {useLocale,type Label} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,useAction,useLoad} from '@/components/common';
const blank={slug:'',name_ru:'',name_kk:'',name_en:'',description_ru:'',active:true};
function DirectionForm({item,onSaved}:{item?:Direction;onSaved:()=>Promise<void>}){const {t}=useLocale();const action=useAction();const [draft,setDraft]=useState(item?{slug:item.slug,name_ru:item.name_ru,name_kk:item.name_kk,name_en:item.name_en,description_ru:item.description_ru,active:item.active}:blank);async function submit(event:FormEvent){event.preventDefault();await action.run(async()=>{const {slug,...changes}=draft;await mutate(item?`/admin/directions/${item.id}`:'/admin/directions',item?changes:draft,item?'PATCH':'POST');if(!item)setDraft(blank);await onSaved();});}return <form className="form-grid" onSubmit={submit}><div className="full-width"><ActionNotice action={action}/></div>{(['slug','name_ru','name_kk','name_en'] as const).map((key,index)=><Field key={key} label={t((['slug','nameRu','nameKk','nameEn'] as Label[])[index])}><input required disabled={!!item&&key==='slug'} maxLength={key==='slug'?60:160} pattern={key==='slug'?'[a-z][a-z0-9-]{1,59}':undefined} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}<div className="full-width"><Field label={t('descriptionRu')}><textarea maxLength={3000} value={draft.description_ru} onChange={e=>setDraft({...draft,description_ru:e.target.value})}/></Field></div><label className="check-row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>{t('active')}</label><div className="full-width"><Button type="submit" disabled={action.busy}>{t(item?'save':'createDirection')}</Button></div></form>;}
function Directions(){const {t,locale}=useLocale();const load=useLoad(()=>api<Direction[]>('/admin/directions'));const [editing,setEditing]=useState('');return <div className="stack"><section className="panel"><h2>{t('createDirection')}</h2><DirectionForm onSaved={load.reload}/></section><DataState {...load} retry={load.reload}>{load.data?.length?<div className="grid-2">{load.data.map(item=><article className="card" key={item.id}><div className="row"><h3>{item[`name_${locale}`]}</h3><Badge tone={item.active?'success':'warning'}>{t(item.active?'active':'disabled')}</Badge></div><p>{item.name_ru} · {item.name_kk} · {item.name_en}</p><p>{item.description_ru}</p><Button variant="secondary" onClick={()=>setEditing(editing===item.id?'':item.id)}>{t(editing===item.id?'cancel':'edit')}</Button>{editing===item.id&&<div style={{marginTop:24}}><DirectionForm item={item} onSaved={load.reload}/></div>}</article>)}</div>:<NoData/>}</DataState></div>;}
export default function Page(){return <AdminShell title="directions"><Directions/></AdminShell>;}
