'use client';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {api,ApiError} from '@/lib/api';
import {useLocale} from '@/lib/i18n';
import {Button,EmptyState} from './ui';
export function useLoad<T>(loader:()=>Promise<T>,deps:unknown[]=[]){const [data,setData]=useState<T>();const [error,setError]=useState<unknown>();const [loading,setLoading]=useState(true);const reload=useCallback(async()=>{setLoading(true);setError(undefined);try{setData(await loader());}catch(value){setError(value);}finally{setLoading(false);}},deps);useEffect(()=>{let live=true;setLoading(true);setError(undefined);loader().then(value=>{if(live)setData(value);}).catch(value=>{if(live)setError(value);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},deps);return {data,error,loading,reload,setData};}
export function ErrorNotice({error}:{error:unknown}){const {t}=useLocale();const status=error instanceof ApiError?error.status:500;return <div className="error" role="alert"><strong>{t(status===401?'sessionExpired':status===403?'denied':status===0?'network':'error')}</strong>{error instanceof ApiError&&error.requestId&&<p>{t('requestId')}: <code style={{overflowWrap:'anywhere'}}>{error.requestId}</code></p>}{error instanceof Error&&<details><summary>{t('technicalDetails')}</summary><p>{error.message}</p></details>}</div>;}
export function DataState({loading,error,retry,children}:{loading:boolean;error:unknown;retry:()=>void;children:ReactNode}){const {t}=useLocale();if(loading)return <div className="loading-state" role="status"><div className="spinner"/>{t('loading')}</div>;if(error)return <><ErrorNotice error={error}/><Button variant="secondary" onClick={retry}>{t('retry')}</Button></>;return <>{children}</>;}
export function useAction(){const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();const [success,setSuccess]=useState(false);async function run(work:()=>Promise<unknown>){if(busy)return false;setBusy(true);setError(undefined);setSuccess(false);try{await work();setSuccess(true);return true;}catch(value){setError(value);return false;}finally{setBusy(false);}}return {busy,error,success,run,clear:()=>{setError(undefined);setSuccess(false);}};}
export function ActionNotice({action}:{action:ReturnType<typeof useAction>}){const {t}=useLocale();return <>{Boolean(action.error)&&<ErrorNotice error={action.error}/>} {action.success&&<div className="success" role="status">{t('saved')}</div>}</>;}
export function usePaged<T>(path:string){const [page,setPage]=useState(0);useEffect(()=>setPage(0),[path]);const load=useLoad(()=>api<T[]>(`${path}${path.includes('?')?'&':'?'}limit=25&offset=${page*25}`),[path,page]);return {...load,page,setPage};}
export function Pager({page,setPage,hasNext}:{page:number;setPage:(page:number)=>void;hasNext:boolean}){const {t}=useLocale();return <nav className="pager" aria-label={t('page')}><Button variant="secondary" disabled={!page} onClick={()=>setPage(page-1)}>{t('previous')}</Button><span>{t('page')} {page+1}</span><Button variant="secondary" disabled={!hasNext} onClick={()=>setPage(page+1)}>{t('next')}</Button></nav>;}
export function NoData(){const {t}=useLocale();return <EmptyState title={t('noData')}/>;}
export function LocalePicker(){const {locale,setLocale,t}=useLocale();return <select className="locale-select" value={locale} aria-label={t('language')} onChange={e=>setLocale(e.target.value as 'ru'|'kk'|'en')}><option value="ru">RU</option><option value="kk">KZ</option><option value="en">EN</option></select>;}
export const webUrl=(process.env.NEXT_PUBLIC_WEB_URL||'http://127.0.0.1:3000').replace(/\/$/,'');

