'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState,type ReactNode} from 'react';
import {Activity,ArrowUpRight,BarChart3,BookOpen,ClipboardCheck,FileCheck2,FileText,FolderOpen,History,LayoutDashboard,LifeBuoy,LogOut,Menu,ShieldCheck,Users,X} from 'lucide-react';
import {api,ApiError,mutate} from '@/lib/api';
import type {User} from '@/lib/types';
import {useLocale,type Label} from '@/lib/i18n';
import {Button} from './ui';
import {DataState,ErrorNotice,LocalePicker,useLoad,webUrl} from './common';
const nav:[string,Label,typeof LayoutDashboard][]=[['/','overview',LayoutDashboard],['/launch','launch',ClipboardCheck],['/users','users',Users],['/registrations','registrations',ClipboardCheck],['/projects','projects',FolderOpen],['/growth','growth',BookOpen],['/ai-review','aiReview',ClipboardCheck],['/directions','directions',BookOpen],['/documents','documents',FileText],['/activity','activity',Activity],['/results','results',FileCheck2],['/comments','comments',FileText],['/reports','reports',LifeBuoy],['/privacy','privacy',ShieldCheck],['/analytics','analytics',BarChart3],['/audit','audit',History],['/operations','operations',Activity]];
export function AdminShell({children,title,description}:{children:ReactNode;title:Label;description?:Label}){const {t}=useLocale();const rawPathname=usePathname();const basePath=process.env.NEXT_PUBLIC_ADMIN_BASE_PATH||'';const pathname=basePath&&rawPathname.startsWith(basePath+'/')?rawPathname.slice(basePath.length):rawPathname===basePath?'/':rawPathname;const router=useRouter();const [open,setOpen]=useState(false);const [loggingOut,setLoggingOut]=useState(false);const load=useLoad(()=>api<User>('/admin/me'),[pathname]);const health=useLoad(()=>api<{demo_mode:boolean;environment:string}>('/health'));const [logoutError,setLogoutError]=useState<unknown>();async function logout(){setLoggingOut(true);try{await mutate('/auth/logout');router.push('/login');router.refresh();}catch(error){setLogoutError(error);}finally{setLoggingOut(false);}}
return <div className="admin-layout"><aside className={`admin-sidebar ${open?'is-open':''}`}><Link className="brand" href="/">DanaConnect<span>{t('administration')}</span></Link><button className="icon-button mobile-menu sidebar-close" aria-label={t('cancel')} onClick={()=>setOpen(false)}><X size={20}/></button><p className="sidebar-caption">{t('workspace')}</p><nav aria-label={t('administration')}>{nav.map(([href,key,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={pathname===href?'active':''}><Icon size={19}/>{t(key)}</Link>)}</nav><div className="sidebar-user"><ShieldCheck size={25}/><div><strong>{load.data?.full_name||t('admin')}</strong><small>{t('security')}</small></div></div></aside><div className="admin-body"><header className="admin-topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label={t('administration')} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><span className="topbar-product">DanaConnect</span><span className="topbar-divider"/><span>{t('administration')}</span></div><div className="topbar-actions"><LocalePicker/><a className="text-link topbar-platform" href={webUrl} target="_blank" rel="noopener noreferrer">{t('backToPlatform')}<ArrowUpRight size={15}/></a>{load.data&&<button className="icon-button" disabled={loggingOut} onClick={logout} aria-label={t('logout')}><LogOut size={19}/></button>}</div></header><main className="admin-main">{health.data?.demo_mode&&<div className="notice notice-demo"><strong>{t('demo')}</strong> · {t('demoWarning')}</div>}{Boolean(logoutError)&&<ErrorNotice error={logoutError}/>}<div className="page-heading"><p className="eyebrow">DANACONNECT · ADMIN</p><h1>{t(title)}</h1>{description&&<p className="muted">{t(description)}</p>}</div><DataState {...load} retry={load.reload}>{load.data?children:<div className="panel"><p>{t('denied')}</p></div>}</DataState>{load.error instanceof ApiError&&(load.error.status===401||load.error.status===403)&&<div className="actions"><Button href={`/login?returnTo=${encodeURIComponent(pathname)}`}>{t('login')}</Button><Button variant="secondary" onClick={logout} disabled={loggingOut}>{t('logout')}</Button></div>}</main><footer className="admin-footer">DanaConnect · {t('workspace')}</footer></div></div>;
}

