'use client';
import {Fragment,useState} from 'react';
import {mutate} from '@/lib/api';
import type {PrivacyRequest} from '@/lib/admin-types';
import {useLocale,dateTime} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,Pager,useAction,usePaged} from '@/components/common';
function PrivacyReview({request,refresh}:{request:PrivacyRequest;refresh:()=>Promise<void>}){const {t}=useLocale();const action=useAction();const [status,setStatus]=useState('reviewing');const [reason,setReason]=useState('');return <form className="form-grid" onSubmit={e=>{e.preventDefault();action.run(async()=>{await mutate(`/admin/privacy-requests/${request.id}`,{status,reason},'PATCH');await refresh();});}}><div className="full-width"><ActionNotice action={action}/><div className="notice">{t('privacyWarning')}</div></div><Field label={t('status')}><select value={status} onChange={e=>setStatus(e.target.value)}><option value="reviewing">{t('reviewing')}</option>{request.kind!=='erase'&&<option value="fulfilled">{t('completed')}</option>}<option value="rejected">{t('rejected')}</option></select></Field><Field label={t('reason')}><textarea required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button type="submit" disabled={action.busy}>{t('save')}</Button></form>;}
function Privacy(){const {t,label,locale}=useLocale();const [selected,setSelected]=useState('');const load=usePaged<PrivacyRequest>('/admin/privacy-requests');return <DataState {...load} retry={load.reload}>{load.data?.length?<div className="table-wrap"><table><thead><tr><th>{t('users')}</th><th>{t('requestType')}</th><th>{t('reason')}</th><th>{t('status')}</th><th>{t('created')}</th><th>{t('action')}</th></tr></thead><tbody>{load.data.map(request=><Fragment key={request.id}><tr><td className="word-break">{request.full_name||request.email||request.user_id}</td><td>{label(request.kind)}</td><td className="pre-line">{request.reason||'—'}{request.review_reason&&<small>{t('reason')}: {request.review_reason}</small>}</td><td><Badge>{label(request.status)}</Badge></td><td>{dateTime(request.created_at,locale)}</td><td><Button variant="secondary" disabled={['fulfilled','rejected'].includes(request.status)} onClick={()=>setSelected(selected===request.id?'':request.id)}>{t('edit')}</Button></td></tr>{selected===request.id&&<tr><td colSpan={6}><PrivacyReview request={request} refresh={load.reload}/></td></tr>}</Fragment>)}</tbody></table></div>:<NoData/>}<Pager {...load} hasNext={load.data?.length===25}/></DataState>;}
export default function Page(){return <AdminShell title="privacy"><Privacy/></AdminShell>;}

