'use client';
import {useState} from 'react';
import {mutate,safeUrl} from '@/lib/api';
import type {User} from '@/lib/types';
import {useLocale,dateTime} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,Pager,useAction,usePaged} from '@/components/common';
function Review({user,refresh}:{user:User;refresh:()=>Promise<void>}){const {t,label,locale}=useLocale();const action=useAction();const [reason,setReason]=useState('');return <article className="card"><div className="row"><h3>{user.full_name}</h3><Badge tone="blue">{label(user.role)}</Badge></div><p>{user.email} · {user.city} · {user.timezone}</p>{user.birth_date&&<p>{t('birthDate')}: {new Intl.DateTimeFormat(locale==='kk'?'kk-KZ':locale==='ru'?'ru-RU':'en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(user.birth_date))}</p>}<h4>{t('bio')}</h4><p className="pre-line">{user.bio}</p>{user.role==='mentor'&&<><h4>{t('expertise')}</h4><p className="pre-line">{user.expertise}</p><p>{t('capacity')}: {user.capacity}</p>{user.evidence_urls?.map((url,index)=>safeUrl(url)&&<p key={index}><a className="text-link" href={safeUrl(url)} target="_blank" rel="noopener noreferrer">{t('evidence')} {index+1}</a></p>)}</>}<hr className="divider"/><ActionNotice action={action}/><Field label={t('reason')}><textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions"><Button disabled={action.busy} onClick={()=>action.run(async()=>{await mutate(`/admin/registrations/${user.id}/review`,{decision:'approved',reason});await refresh();})}>{t('approve')}</Button><Button disabled={action.busy||!reason.trim()} variant="secondary" onClick={()=>action.run(async()=>{await mutate(`/admin/registrations/${user.id}/review`,{decision:'changes_requested',reason});await refresh();})}>{t('changesRequested')}</Button></div></article>;}
function Registrations(){const load=usePaged<User>('/admin/registrations');return <DataState {...load} retry={load.reload}>{load.data?.length?<div className="grid-2">{load.data.map(user=><Review key={user.id} user={user} refresh={load.reload}/>)}</div>:<NoData/>}<Pager {...load} hasNext={load.data?.length===25}/></DataState>;}
export default function Page(){return <AdminShell title="registrations" description="registrationNote"><Registrations/></AdminShell>;}
