'use client';
import {Fragment,useState,type FormEvent} from 'react';
import {mutate} from '@/lib/api';
import type {AdminUser} from '@/lib/admin-types';
import {useLocale} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,Pager,useAction,usePaged} from '@/components/common';
function UserChanges({user,refresh,onStatus}:{user:AdminUser;refresh:()=>Promise<void>;onStatus:(status:string)=>void}){const {t}=useLocale();const action=useAction();const [role,setRole]=useState(user.role==='mentor'?'mentee':'mentor');const [reason,setReason]=useState('');async function status(event:FormEvent){event.preventDefault();await action.run(async()=>{const updated=await mutate<AdminUser>(`/admin/users/${user.id}/status`,{status:user.account_status==='suspended'?'active':'suspended',reason},'PATCH');onStatus(updated.account_status);await refresh();});}return <div className="form-stack"><ActionNotice action={action}/><div className="notice">{t('suspendNotice')}<p>{t('roleNotice')}</p></div><Field label={t('reason')}><textarea required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="form-grid"><Field label={t('role')}><select value={role} onChange={e=>setRole(e.target.value)}><option value="mentor">{t('mentor')}</option><option value="mentee">{t('mentee')}</option></select></Field><div className="actions"><Button disabled={action.busy||reason.trim().length<5||role===user.role} onClick={()=>action.run(async()=>{await mutate(`/admin/users/${user.id}/role`,{role,reason},'PATCH');await refresh();})} variant="secondary">{t('changeRole')}</Button></div></div><form onSubmit={status}><Button type="submit" variant={user.account_status==='suspended'?'primary':'danger'} disabled={action.busy||reason.trim().length<5}>{t(user.account_status==='suspended'?'reactivate':'suspend')}</Button></form></div>;}
function Users(){const {t,label}=useLocale();const [q,setQ]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState('');const [updatedStatus,setUpdatedStatus]=useState('');const load=usePaged<AdminUser>(`/admin/users?q=${encodeURIComponent(query)}`);return <div className="stack"><form className="filters" onSubmit={e=>{e.preventDefault();setQuery(q);}}><input aria-label={t('search')} placeholder={`${t('name')} / ${t('email')}`} value={q} onChange={e=>setQ(e.target.value)}/><Button type="submit">{t('search')}</Button><Button variant="secondary" onClick={load.reload}>{t('refresh')}</Button></form>{updatedStatus&&<div className="success" role="status">{t('saved')} · {t('status')}: <strong>{label(updatedStatus)}</strong></div>}<DataState {...load} retry={load.reload}>{!load.data?.length?<NoData/>:<div className="table-wrap"><table><thead><tr><th>{t('users')}</th><th>{t('role')}</th><th>{t('status')}</th><th>{t('directions')}</th><th>{t('action')}</th></tr></thead><tbody>{load.data.map(user=><Fragment key={user.id}><tr><td><strong>{user.full_name||user.email}</strong><small>{user.email}</small><small>{user.city} · {user.timezone}</small></td><td><Badge tone="blue">{label(user.role)}</Badge></td><td><Badge tone={user.account_status==='active'?'success':user.account_status==='suspended'?'danger':'warning'}>{label(user.account_status)}</Badge></td><td>{user.direction_ids.length}</td><td><Button variant="secondary" disabled={user.role==='admin'} onClick={()=>setSelected(selected===user.id?'':user.id)}>{t('edit')}</Button></td></tr>{selected===user.id&&<tr><td colSpan={5}><UserChanges user={user} refresh={load.reload} onStatus={setUpdatedStatus}/></td></tr>}</Fragment>)}</tbody></table></div>}<Pager {...load} hasNext={load.data?.length===25}/></DataState></div>;}
export default function Page(){return <AdminShell title="users"><Users/></AdminShell>;}


