'use client';
import {api} from '@/lib/api';
import {useLocale} from '@/lib/i18n';
import {AppShell} from '@/components/shell';
import {Badge} from '@/components/ui';
import {LoadState,useLoad} from '@/components/workflows/common';

type Stats={demo_mode:boolean;mentors:number;mentees:number;projects:number;completed_results:number;verified_results:number;completed_meetings:number;showcase_projects:number};
const copy={
  ru:{title:'Отчёт платформы',description:'Общие показатели работы сообщества без личных сведений участников.',demo:'Учебные данные',note:'Эти цифры относятся к вымышленным участникам и демонстрируют работу отчёта.',mentors:'Одобренные менторы',mentees:'Одобренные менти',projects:'Опубликованные проекты',completed_results:'Завершённые участия',verified_results:'Подтверждённые результаты',completed_meetings:'Подтверждённые встречи',showcase_projects:'Проекты в витрине',definitions:'Как считаем',meeting:'Встречи учитываются после подтверждения ментором. Результат считается подтверждённым после проверки успешного завершения участия.',showcase:'Витрина включает только проверенные результаты с актуальными согласиями всех необходимых участников.'},
  kk:{title:'Платформа есебі',description:'Қатысушылардың жеке мәліметтерінсіз қауымдастық жұмысының жалпы көрсеткіштері.',demo:'Оқу деректері',note:'Бұл сандар ойдан шығарылған қатысушыларға қатысты және есептің жұмысын көрсетеді.',mentors:'Мақұлданған менторлар',mentees:'Мақұлданған менти',projects:'Жарияланған жобалар',completed_results:'Аяқталған қатысулар',verified_results:'Расталған нәтижелер',completed_meetings:'Расталған кездесулер',showcase_projects:'Көрмедегі жобалар',definitions:'Қалай есептейміз',meeting:'Кездесулер ментор растағаннан кейін есептеледі. Нәтиже қатысудың сәтті аяқталуын тексергеннен кейін расталған болып саналады.',showcase:'Көрмеге барлық қажетті қатысушылардың өзекті келісімдері бар тексерілген нәтижелер ғана кіреді.'},
  en:{title:'Platform report',description:'Overall community activity without participants’ personal information.',demo:'Demonstration data',note:'These figures describe fictional participants and demonstrate how the report works.',mentors:'Approved mentors',mentees:'Approved mentees',projects:'Published projects',completed_results:'Completed participations',verified_results:'Verified outcomes',completed_meetings:'Confirmed meetings',showcase_projects:'Showcase projects',definitions:'How we count',meeting:'Meetings are counted after the mentor confirms them. An outcome is verified after a successful participation is reviewed.',showcase:'The showcase includes reviewed outcomes with current consent from every required participant.'}
};
export default function ImpactPage(){const {locale}=useLocale();const t=copy[locale];const load=useLoad(()=>api<Stats>('/stats'));const keys=['mentors','mentees','projects','completed_results','verified_results','completed_meetings','showcase_projects']as const;return <AppShell title={t.title} description={t.description}><div className="container page-content"><LoadState {...load} retry={load.reload}>{load.data&&<><div className="stack">{load.data.demo_mode&&<div className="notice"><Badge tone="warning">{t.demo}</Badge><p>{t.note}</p></div>}<div className="cards-grid">{keys.map(key=><article className="card" key={key}><h2>{new Intl.NumberFormat(locale).format(load.data![key])}</h2><p>{t[key]}</p></article>)}</div><section className="panel"><h2>{t.definitions}</h2><p>{t.meeting}</p><p>{t.showcase}</p></section></div></>}</LoadState></div></AppShell>;}
