"""support replies and explicit message receipts

Revision ID: 0e82eab8e5ef
Revises: 1639a031a3c6
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e82eab8e5ef'
down_revision: Union[str, None] = '1639a031a3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_responses_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_responses_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index('ix_report_responses_time', ['report_id', 'created_at'], unique=False)

    op.create_table('message_reads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_message_read_user_message')
    )
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reads_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reads_message_id'))

    op.drop_table('message_reads')
    with op.batch_alter_table('report_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_report_responses_time')
        batch_op.drop_index(batch_op.f('ix_report_responses_sender_id'))
        batch_op.drop_index(batch_op.f('ix_report_responses_report_id'))

    op.drop_table('report_responses')
    # ### end Alembic commands ###
