"""calendar_collaboration_growth_ai_worker

Revision ID: 1639a031a3c6
Revises: a6a433a7debd
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1639a031a3c6'
down_revision: Union[str, None] = 'a6a433a7debd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_counters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('count >= 0', name='ck_ai_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'scope_key', name='uq_ai_daily_scope')
    )
    with op.batch_alter_table('ai_usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_counters_day'), ['day'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('idle','running','success','failed')", name='ck_worker_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('allow_admin_review', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('subject_user_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('source_facts', sa.JSON(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('override_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('structure','mentor_recommendation','profile_review')", name='ck_ai_proposal_kind'),
    sa.CheckConstraint("status IN ('pending','ready','failed','approved','dismissed','overridden')", name='ck_ai_proposal_status'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_proposals_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_proposals_subject_user_id'), ['subject_user_id'], unique=False)

    op.create_table('availability_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('dst_fold', sa.String(length=10), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('generated_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("dst_fold IN ('first','second')", name='ck_availability_fold'),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_interval'),
    sa.CheckConstraint('horizon_weeks BETWEEN 1 AND 12', name='ck_availability_horizon'),
    sa.CheckConstraint('revision >= 1', name='ck_availability_revision'),
    sa.CheckConstraint('slot_minutes BETWEEN 15 AND 120', name='ck_availability_duration'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_availability_weekday'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_rules_mentor_id'), ['mentor_id'], unique=False)

    op.create_table('growth_privacy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('leaderboard_visible', sa.Boolean(), nullable=False),
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('consent_version', sa.String(length=40), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('learning_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('direction_id', sa.String(length=36), nullable=True),
    sa.Column('title_ru', sa.String(length=220), nullable=False),
    sa.Column('title_kk', sa.String(length=220), nullable=False),
    sa.Column('title_en', sa.String(length=220), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('description_kk', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('content_language', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('article','video','course','guide')", name='ck_material_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_materials_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_materials_direction_id'), ['direction_id'], unique=False)

    op.create_table('point_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('completed_meeting','verified_result')", name='ck_point_source'),
    sa.CheckConstraint('points > 0', name='ck_point_amount'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', name='uq_point_source')
    )
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_events_user_id'), ['user_id'], unique=False)

    op.create_table('generated_rule_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_key', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['availability_rules.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'occurrence_key', name='uq_rule_occurrence'),
    sa.UniqueConstraint('slot_id')
    )
    with op.batch_alter_table('generated_rule_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_rule_slots_rule_id'), ['rule_id'], unique=False)

    op.create_table('private_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=180), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','deleted')", name='ck_attachment_status'),
    sa.CheckConstraint('size_bytes > 0', name='ck_attachment_size'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('private_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_private_attachments_project_id'), ['project_id'], unique=False)

    op.create_table('project_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope IN ('public','team')", name='ck_comment_scope'),
    sa.CheckConstraint("status IN ('pending','visible','hidden')", name='ck_comment_status'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_comments_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_project_comments_time', ['project_id', 'created_at'], unique=False)

    op.create_table('team_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('target_email', sa.String(length=320), nullable=False),
    sa.Column('member_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_outbox_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','declined','revoked','expired')", name='ck_invitation_status'),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['email_outbox_id'], ['email_outbox.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_target_email'), ['target_email'], unique=False)
        batch_op.create_index('uq_pending_project_invitation', ['project_id', 'target_email'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))

    op.create_table('booking_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=True),
    sa.Column('email_outbox_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("delivery_status IN ('email_queued','in_app_only')", name='ck_reminder_delivery'),
    sa.CheckConstraint("kind IN ('24h','1h')", name='ck_reminder_kind'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['email_outbox_id'], ['email_outbox.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'user_id', 'kind', name='uq_booking_user_reminder'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('booking_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_reminders_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('growth_awards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title_ru', sa.String(length=220), nullable=False),
    sa.Column('title_kk', sa.String(length=220), nullable=False),
    sa.Column('title_en', sa.String(length=220), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('description_kk', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('issued_name', sa.String(length=180), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("kind <> 'certificate' OR result_id IS NOT NULL", name='ck_certificate_result'),
    sa.CheckConstraint("kind IN ('nomination','certificate')", name='ck_growth_award_kind'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'result_id', 'kind', name='uq_user_result_award')
    )
    with op.batch_alter_table('growth_awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_awards_result_id'), ['result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_growth_awards_user_id'), ['user_id'], unique=False)

    op.bulk_insert(sa.table("worker_heartbeats", sa.column("id", sa.String(50)),
        sa.column("status", sa.String(20)), sa.column("summary", sa.JSON())),
        [{"id": "calendar", "status": "idle", "summary": {}}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_awards_user_id'))
        batch_op.drop_index(batch_op.f('ix_growth_awards_result_id'))

    op.drop_table('growth_awards')
    with op.batch_alter_table('booking_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reminders_booking_id'))

    op.drop_table('booking_reminders')
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.drop_index('uq_pending_project_invitation', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_team_invitations_target_email'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_project_id'))

    op.drop_table('team_invitations')
    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_project_comments_time')
        batch_op.drop_index(batch_op.f('ix_project_comments_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_comments_author_id'))

    op.drop_table('project_comments')
    with op.batch_alter_table('private_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_attachments_project_id'))

    op.drop_table('private_attachments')
    with op.batch_alter_table('generated_rule_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_rule_slots_rule_id'))

    op.drop_table('generated_rule_slots')
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_events_user_id'))

    op.drop_table('point_events')
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_materials_direction_id'))
        batch_op.drop_index(batch_op.f('ix_learning_materials_active'))

    op.drop_table('learning_materials')
    op.drop_table('growth_privacy')
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_rules_mentor_id'))

    op.drop_table('availability_rules')
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_proposals_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_ai_proposals_requester_id'))

    op.drop_table('ai_proposals')
    op.drop_table('ai_preferences')
    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('ai_usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_counters_day'))

    op.drop_table('ai_usage_counters')
    # ### end Alembic commands ###
