"""delivery_mfa_locale_privacy

Revision ID: a6a433a7debd
Revises: 0001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6a433a7debd'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','leased','sent','failed')", name='ck_outbox_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_outbox_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_due', ['status', 'next_attempt_at'], unique=False)

    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_hash', sa.String(length=128), nullable=False),
    sa.Column('nonce_hash', sa.String(length=128), nullable=False),
    sa.Column('browser_hash', sa.String(length=128), nullable=False),
    sa.Column('encrypted_verifier', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_table('admin_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_totp_secret', sa.Text(), nullable=False),
    sa.Column('last_used_step', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('external_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_external_identity_subject')
    )
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identities_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('privacy_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('export','deactivate','erase')", name='ck_privacy_kind'),
    sa.CheckConstraint("status IN ('pending','reviewing','fulfilled','rejected')", name='ck_privacy_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_requests_user_id'), ['user_id'], unique=False)

    op.create_table('session_assurances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.String(length=2), server_default='ru', nullable=False))
        batch_op.add_column(sa.Column('presented_content_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_kk', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_locale', sa.String(length=2), server_default='ru', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_locale')

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_column('content_en')
        batch_op.drop_column('content_kk')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_column('presented_content_hash')
        batch_op.drop_column('locale')

    op.drop_table('session_assurances')
    with op.batch_alter_table('privacy_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_privacy_requests_status'))

    op.drop_table('privacy_requests')
    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_challenges_user_id'))

    op.drop_table('mfa_challenges')
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_identities_user_id'))

    op.drop_table('external_identities')
    op.drop_table('admin_credentials')
    op.drop_table('oauth_states')
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_due')

    op.drop_table('email_outbox')
    # ### end Alembic commands ###
