import type {Operations,OperationSignalCode,DeliveryFailureCode} from './admin-types';
import type {Locale} from './i18n';

const phrases={
  snapshot:['Снимок сервера','Сервер күйінің көшірмесі','Server snapshot'],
  snapshotNote:['Данные на момент запроса. Обновление только вручную.','Сұрау кезіндегі деректер. Тек қолмен жаңартылады.','Data at the time of the request. Refresh manually.'],
  export:['Скачать диагностику (JSON)','Диагностиканы жүктеу (JSON)','Download diagnostics (JSON)'],
  exportNote:['В файле только сводные показатели, время и коды состояния.','Файлда тек жиынтық көрсеткіштер, уақыт және күй кодтары бар.','The file contains only aggregate metrics, timestamps and status codes.'],
  exportError:['Не удалось скачать файл диагностики. Повторите действие.','Диагностика файлын жүктеу мүмкін болмады. Қайталап көріңіз.','Could not download diagnostics. Try again.'],
  exportPrepared:['Файл диагностики подготовлен для скачивания.','Диагностика файлы жүктеуге дайындалды.','Diagnostics file prepared for download.'],
  testEnvironment:['Тестовая среда','Тест ортасы','Test environment'],
  workerFailedStatus:['Цикл завершился с ошибкой','Цикл қатемен аяқталды','Cycle failed'],
  signals:['Требует внимания','Назар аудару қажет','Needs attention'],
  noSignals:['В этом снимке предупреждений нет','Бұл көшірмеде ескертулер жоқ','No warnings in this snapshot'],
  signalNote:['Индикаторы используют пороги 5 минут для worker и 15 минут для очереди писем. Это ориентиры для оператора, а не SLA.','Индикатор шектері: worker үшін 5 минут, хат кезегі үшін 15 минут. Бұл операторға арналған бағдар, SLA емес.','Indicators use 5 minutes for the worker and 15 minutes for due email. These guide operators; they are not an SLA.'],
  warning:['Предупреждение','Ескерту','Warning'],critical:['Критично','Маңызды ақау','Critical'],
  delivery:['Отправка писем','Хат жіберу','Email delivery'],
  deliveryNote:['«Принято провайдером» означает принятие письма сервисом отправки. Доставку во входящие этот снимок не подтверждает.','«Провайдер қабылдады» хатты жіберу сервисі қабылдағанын білдіреді. Бұл көшірме кіріс жәшігіне жеткізуді растамайды.','“Accepted by provider” means the sending service accepted the message. This snapshot does not confirm inbox delivery.'],
  pending:['Ожидают обработки','Өңдеуді күтуде','Pending'],leased:['Взяты worker в обработку','Worker өңдеуге алды','Claimed by worker'],sent:['Принято провайдером','Провайдер қабылдады','Accepted by provider'],failed:['Завершены с ошибкой','Қатемен аяқталды','Failed'],
  due_pending:['Готовы к следующей попытке','Келесі әрекетке дайын','Due for an attempt'],expired_pending:['Срок отправки истёк в очереди','Кезектегі жіберу мерзімі өтті','Expired pending messages'],expired_leases:['Истёк срок захвата worker','Worker өңдеу мерзімі өтті','Expired worker leases'],
  oldest_pending_at:['Самое старое ожидающее письмо','Ең ескі күтілген хат','Oldest pending message'],oldest_due_at:['Самая ранняя готовая попытка','Ең ерте дайын әрекет','Earliest due attempt'],oldest_due_age_seconds:['Задержка самой ранней попытки','Ең ерте әрекеттің кідірісі','Oldest due attempt age'],
  failures_last_24h:['Ошибки у писем, созданных за 24 часа','24 сағатта жасалған хаттардағы қателер','Failed messages created within 24 hours'],
  failureNote:['Считаются текущие ошибки писем, созданных за последние 24 часа; время возникновения ошибки не учитывается. Группы ниже охватывают все текущие ошибки.','Соңғы 24 сағатта жасалған хаттардың ағымдағы қателері есептеледі; қате пайда болған уақыт есептелмейді. Төмендегі топтар барлық ағымдағы қателерді қамтиды.','This counts currently failed messages created within 24 hours, not failures occurring within that period. The groups below cover all current failures.'],
  failureGroups:['Группы ошибок','Қате топтары','Failure groups'],failureCode:['Причина','Себеп','Reason'],count:['Количество','Саны','Count'],noFailures:['Текущих ошибок нет','Ағымдағы қателер жоқ','No current failures'],
  cancellationNote:['В итогах также учитываются письма об отменённых встречах и отозванных приглашениях. Эти отмены сами по себе не вызывают предупреждение об ошибке отправки.','Қорытындыға болдырылмаған кездесулер мен қайтарылған шақырулардың хаттары да кіреді. Бұл әрекеттер өздігінен жіберу қатесі туралы ескерту тудырмайды.','Totals also include messages for cancelled meetings and revoked invitations. Those cancellations alone do not trigger a delivery failure warning.'],
  last_started_at:['Начало последнего цикла','Соңғы циклдің басталуы','Latest cycle started'],last_finished_at:['Завершение последнего цикла','Соңғы циклдің аяқталуы','Latest cycle finished'],age_seconds:['Время после завершения','Аяқталғаннан кейінгі уақыт','Age since completion'],duration_seconds:['Длительность завершённого цикла','Аяқталған циклдің ұзақтығы','Completed cycle duration'],running_age_seconds:['Длительность текущего цикла','Ағымдағы циклдің ұзақтығы','Current running duration'],
  workerNote:['Успешное завершение цикла не означает успешную отправку всех писем. Смотрите счётчики и состояние очереди.','Циклдің сәтті аяқталуы барлық хаттың жіберілгенін білдірмейді. Есептегіштер мен кезек күйін қараңыз.','A successful cycle does not mean every email was sent. Review its counters and the queue state.'],
  summary:['Последние записанные счётчики цикла','Циклдің соңғы жазылған есептегіштері','Latest recorded cycle counters'],
  summaryNote:['Во время выполнения worker здесь остаются счётчики предыдущего завершённого цикла.','Worker жұмыс істеп тұрғанда мұнда алдыңғы аяқталған циклдің есептегіштері қалады.','While the worker is running, these remain the counters from the previous completed cycle.'],
  rules:['Генерация расписания','Кестені қалыптастыру','Schedule generation'],reminders:['Напоминания','Еске салулар','Reminders'],email:['Письма','Хаттар','Email'],
  processed:['Обработано','Өңделді','Processed'],created:['Создано','Жасалды','Created'],skipped:['Пропущено','Өткізілді','Skipped'],errors:['Ошибок','Қателер','Errors'],email_queued:['Писем поставлено в очередь','Хат кезекке қойылды','Emails queued'],in_app_only:['Только внутри платформы','Тек платформа ішінде','In-app only'],claimed:['Взято в обработку','Өңдеуге алынды','Claimed'],retried:['Назначена повторная попытка','Қайта әрекет тағайындалды','Scheduled for retry'],unconfigured:['Почта не настроена','Пошта бапталмаған','Email is unconfigured'],noSummary:['Счётчики ещё не записаны','Есептегіштер әлі жазылмаған','No counters recorded yet'],unknown:['Неизвестно','Белгісіз','Unknown'],
  email_unconfigured:['Почтовый провайдер не настроен','Пошта провайдері бапталмаған','Email provider is not configured'],
  email_due_delayed:['Очередь готовых писем задерживается','Дайын хат кезегі кешігуде','Due email queue is delayed'],
  email_expired_pending:['У писем в очереди истёк срок отправки','Кезектегі хаттардың жіберу мерзімі өтті','Pending messages have expired'],
  email_failed:['Есть письма с завершённой ошибкой','Қатемен аяқталған хаттар бар','Some messages have failed'],
  email_lease_expired:['Worker не завершил обработку в срок','Worker өңдеуді уақытында аяқтамады','Worker claims have expired'],
  worker_missing:['Worker ещё не записал цикл','Worker циклді әлі жазған жоқ','No worker cycle has been recorded'],
  worker_failed:['Последний цикл worker завершился с ошибкой','Worker соңғы циклі қатемен аяқталды','The latest worker cycle failed'],
  worker_stale:['Нет свежего завершённого цикла worker','Worker жаңа аяқталған циклі жоқ','No recent completed worker cycle'],
  worker_running_long:['Текущий цикл worker длится дольше 5 минут','Worker ағымдағы циклі 5 минуттан асты','The current worker cycle exceeds 5 minutes'],
  configureEmail:['Проверьте настройки провайдера и адрес отправителя. После подключения отправьте отдельное пробное письмо и проверьте его получение.','Провайдер баптаулары мен жіберуші мекенжайын тексеріңіз. Қосылған соң сынақ хатын жіберіп, алынғанын тексеріңіз.','Check provider settings and the sender address. After connecting it, send a separate sample message and confirm receipt.'],
  inspectQueue:['Проверьте запуск worker, доступ к базе и ограничения провайдера. Сопоставьте время снимка с журналом цикла.','Worker іске қосылуын, базаға қолжетімділікті және провайдер шектеулерін тексеріңіз. Көшірме уақытын цикл журналымен салыстырыңыз.','Check the worker, database access and provider limits. Compare the snapshot time with the cycle logs.'],
  expiredAdvice:['Проверьте доступность worker. Для истёкшего кода или приглашения участник должен запросить новое через соответствующую форму.','Worker қолжетімділігін тексеріңіз. Мерзімі өткен код не шақыру үшін қатысушы тиісті формада жаңасын сұрауы керек.','Check worker availability. Participants should request a new expired code or invitation through the relevant form.'],
  failureAdvice:['Посмотрите группы ошибок и журналы worker. Исправьте настройку или связь с провайдером; эта страница не повторяет отправку писем.','Қате топтары мен worker журналдарын қараңыз. Баптауды немесе провайдер байланысын түзетіңіз; бұл бет хаттарды қайта жібермейді.','Review failure groups and worker logs. Resolve configuration or provider connectivity; this page does not resend messages.'],
  inspectWorker:['Проверьте внешний планировщик и процесс worker, доступ к базе и журнал последнего цикла. После исправления обновите снимок вручную.','Сыртқы жоспарлаушыны, worker процесін, базаға қолжетімділікті және соңғы цикл журналын тексеріңіз. Түзеткен соң көшірмені қолмен жаңартыңыз.','Check the external scheduler, worker process, database access and latest cycle logs. Refresh manually after resolving the issue.'],
  longAdvice:['Сопоставьте время запуска с журналами и активным процессом. Проверьте ожидание базы или провайдера перед перезапуском.','Іске қосылған уақытты журналдармен және белсенді процеспен салыстырыңыз. Қайта іске қоспас бұрын база не провайдер күтілуін тексеріңіз.','Compare the start time with logs and the active process. Check for database or provider waits before restarting.'],
  attempts_exhausted:['Попытки исчерпаны','Әрекеттер таусылды','Attempts exhausted'],message_expired:['Срок письма истёк','Хат мерзімі өтті','Message expired'],payload_decryption_failed:['Не удалось расшифровать письмо','Хат шифрын ашу мүмкін болмады','Message decryption failed'],provider_missing_receipt:['Провайдер не подтвердил принятие','Провайдер қабылдауды растамады','Provider acceptance missing'],provider_unconfigured:['Провайдер не настроен','Провайдер бапталмаған','Provider unconfigured'],delivery_unexpected:['Непредвиденная ошибка отправки','Күтпеген жіберу қатесі','Unexpected delivery failure'],resend_network:['Ошибка связи с Resend','Resend байланыс қатесі','Resend network failure'],resend_invalid_response:['Некорректный ответ Resend','Resend жауабы қате','Invalid Resend response'],resend_http:['Ошибка HTTP от Resend','Resend HTTP қатесі','Resend HTTP failure'],smtp_recipient_refused:['SMTP отклонил получателя','SMTP алушыны қабылдамады','SMTP recipient refused'],smtp_connection:['Ошибка подключения SMTP','SMTP қосылу қатесі','SMTP connection failure'],smtp_response:['Ошибка ответа SMTP','SMTP жауап қатесі','SMTP response failure'],booking_cancelled:['Встреча отменена','Кездесу болдырылмады','Meeting cancelled'],invitation_revoked:['Приглашение отозвано','Шақыру қайтарылды','Invitation revoked'],other:['Другая причина','Басқа себеп','Other reason'],
} as const;
export type OperationsLabel=keyof typeof phrases;
const localeIndex={ru:0,kk:1,en:2} as const;
export const operationsText=(locale:Locale,key:OperationsLabel)=>phrases[key][localeIndex[locale]];
export const signalAdvice:Record<OperationSignalCode,OperationsLabel>={email_unconfigured:'configureEmail',email_due_delayed:'inspectQueue',email_expired_pending:'expiredAdvice',email_failed:'failureAdvice',email_lease_expired:'inspectQueue',worker_missing:'inspectWorker',worker_failed:'inspectWorker',worker_stale:'inspectWorker',worker_running_long:'longAdvice'};
export const failureCodes:readonly DeliveryFailureCode[]=['attempts_exhausted','message_expired','payload_decryption_failed','provider_missing_receipt','provider_unconfigured','delivery_unexpected','resend_network','resend_invalid_response','resend_http','smtp_recipient_refused','smtp_connection','smtp_response','booking_cancelled','invitation_revoked','other'];
export const readinessKeys=['postgresql','email_configured','google_configured','https_origins','admin_mfa','demo_disabled','debug_codes_disabled','private_storage_configured','legal_documents_configured','worker_recent_success'] as const;
export const countKeys=['users','registrations_pending','privacy_pending','email_pending','email_failed'] as const;
export const summaryKeys={rules:['processed','created','skipped','errors'],reminders:['processed','email_queued','in_app_only','errors'],email:['claimed','sent','retried','failed']} as const;
export function safeTimestamp(value:unknown):string|null {if(typeof value!=='string'||value.length>64||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value))return null;const date=new Date(value);return Number.isFinite(date.getTime())?date.toISOString():null;}
export function safeMetric(value:unknown):number|null {return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=Number.MAX_SAFE_INTEGER?value:null;}
export function safeFailureCode(value:unknown):DeliveryFailureCode {return failureCodes.includes(value as DeliveryFailureCode)?value as DeliveryFailureCode:'other';}

// Only fixed aggregate fields reach the downloaded file. No raw API objects, messages or IDs.
export function operationsDiagnostics(data:Operations){
  const summary:Record<string,Record<string,number|string>>={};
  for(const group of ['rules','reminders','email'] as const){const source=data.worker?.summary?.[group];if(!source)continue;const output:Record<string,number|string>={};for(const key of summaryKeys[group]){const value=safeMetric((source as Record<string,unknown>)[key]);if(value!==null)output[key]=value;}if(group==='email'&&data.worker?.summary.email?.status==='unconfigured')output.status='unconfigured';summary[group]=output;}
  const delivery=data.delivery;
  const worker=data.worker;
  const failures=new Map<DeliveryFailureCode,number>();for(const row of delivery?.failure_codes??[]){const count=safeMetric(row.count);if(count!==null){const code=safeFailureCode(row.code);failures.set(code,(failures.get(code)??0)+count);}}
  return {schema_version:1,observed_at:safeTimestamp(data.observed_at),environment:['development','production','test'].includes(data.environment)?data.environment:'unknown',demo_mode:data.demo_mode===true,
    readiness:Object.fromEntries(readinessKeys.map(key=>[key,data.readiness?.[key]===true])),counts:Object.fromEntries(countKeys.map(key=>[key,safeMetric(data.counts?.[key])])),
    delivery:delivery?{status_counts:Object.fromEntries((['pending','leased','sent','failed'] as const).map(key=>[key,safeMetric(delivery.status_counts?.[key])])),due_pending:safeMetric(delivery.due_pending),expired_pending:safeMetric(delivery.expired_pending),expired_leases:safeMetric(delivery.expired_leases),oldest_pending_at:safeTimestamp(delivery.oldest_pending_at),oldest_due_at:safeTimestamp(delivery.oldest_due_at),oldest_due_age_seconds:safeMetric(delivery.oldest_due_age_seconds),failures_last_24h:safeMetric(delivery.failures_last_24h),failure_codes:Array.from(failures,([code,count])=>({code,count})).sort((a,b)=>a.code.localeCompare(b.code))}:null,
    worker:worker?{status:['idle','running','success','failed'].includes(worker.status)?worker.status:'unknown',last_started_at:safeTimestamp(worker.last_started_at),last_finished_at:safeTimestamp(worker.last_finished_at),recent_success:worker.recent_success===true,age_seconds:safeMetric(worker.age_seconds),duration_seconds:safeMetric(worker.duration_seconds),running_age_seconds:safeMetric(worker.running_age_seconds),summary}:null,
    signals:(data.signals??[]).filter(signal=>Object.hasOwn(signalAdvice,signal.code)&&['warning','critical'].includes(signal.severity)).slice(0,9).map(signal=>({code:signal.code,severity:signal.severity})),
    interpretation:{sent:'provider_accepted_not_inbox_verified',failures_last_24h:'currently_failed_messages_created_within_24h',thresholds:'operator_indicators_not_sla'},
  };
}
