'use client';
import {useState} from 'react';
import {mutate} from '@/lib/api';
import type {Project} from '@/lib/types';
import {useLocale} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,Pager,useAction,usePaged,webUrl} from '@/components/common';
function Review({project,refresh}:{project:Project;refresh:()=>Promise<void>}){const {t,label}=useLocale();const action=useAction();const [reason,setReason]=useState('');return <article className="card"><div className="row"><h3>{project.title}</h3><Badge tone={project.visibility_status==='published'?'success':'warning'}>{label(project.visibility_status)}</Badge></div><p className="pre-line"><strong>{t('problem')}: </strong>{project.problem}</p><p className="pre-line">{project.description}</p><div className="tags">{project.required_skills.map(skill=><Badge key={skill}>{skill}</Badge>)}</div><p style={{marginTop:18}}>{t('capacity')}: {project.capacity}</p><ActionNotice action={action}/><Field label={t('reason')}><textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="actions"><Button disabled={action.busy||project.visibility_status==='published'} onClick={()=>action.run(async()=>{await mutate(`/admin/projects/${project.id}/review`,{decision:'published',reason});await refresh();})}>{t('publish')}</Button><Button variant="secondary" disabled={action.busy||reason.trim().length<3||project.visibility_status==='hidden'} onClick={()=>action.run(async()=>{await mutate(`/admin/projects/${project.id}/review`,{decision:'hidden',reason});await refresh();})}>{t('hide')}</Button><a className="text-link" href={`${webUrl}/projects/${project.id}`} target="_blank" rel="noopener noreferrer">{t('openProject')}</a></div></article>;}
function Projects(){const {t}=useLocale();const [status,setStatus]=useState('pending');const load=usePaged<Project>(`/admin/projects${status?`?status=${status}`:''}`);return <div className="stack"><div className="filters"><select aria-label={t('status')} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t('allStatuses')}</option>{['pending','published','hidden'].map(key=><option key={key} value={key}>{t(key as 'pending'|'published'|'hidden')}</option>)}</select><Button variant="secondary" onClick={load.reload}>{t('refresh')}</Button></div><DataState {...load} retry={load.reload}>{load.data?.length?<div className="grid-2">{load.data.map(project=><Review key={project.id} project={project} refresh={load.reload}/>)}</div>:<NoData/>}<Pager {...load} hasNext={load.data?.length===25}/></DataState></div>;}
export default function Page(){return <AdminShell title="projects" description="moderationNote"><Projects/></AdminShell>;}
