'use client';
import {Fragment,useState} from 'react';
import {mutate} from '@/lib/api';
import type {SupportReport} from '@/lib/admin-types';
import {useLocale,dateTime} from '@/lib/i18n';
import {AdminShell} from '@/components/shell';
import {Badge,Button,Field} from '@/components/ui';
import {ActionNotice,DataState,NoData,Pager,useAction,usePaged} from '@/components/common';
import {ReportConversation} from '@/components/support/conversation';
import {supportText,reportStatus,type SupportPhrase} from '@/components/support/copy';
function ReportReview({report,refresh}:{report:SupportReport;refresh:()=>Promise<void>}){const {t,locale}=useLocale();const action=useAction();const [status,setStatus]=useState(report.status==='pending'?'reviewing':report.status);const [reason,setReason]=useState('');return <form className="form-grid" onSubmit={e=>{e.preventDefault();action.run(async()=>{await mutate(`/admin/reports/${report.id}`,{status,reason:reason.trim()},'PATCH');await refresh();});}}><div className="full-width"><ActionNotice action={action}/><p className="muted">{supportText(locale,'decisionNote')}</p></div><Field label={t('status')}><select value={status} onChange={e=>setStatus(e.target.value)}>{['reviewing','resolved','dismissed'].map(status=><option key={status} value={status}>{t(status as 'reviewing'|'resolved'|'dismissed')}</option>)}</select></Field><Field label={supportText(locale,'decision')}><textarea required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={action.busy||reason.trim().length<5} type="submit">{t('save')}</Button></form>;}
function Reports(){const {t,label,locale}=useLocale();const [selected,setSelected]=useState('');const load=usePaged<SupportReport>('/admin/reports');return <DataState {...load} retry={load.reload}>{load.data?.length?<div className="table-wrap"><table><thead><tr><th>{t('entity')}</th><th>{t('reporter')}</th><th>{t('reason')}</th><th>{t('status')}</th><th>{t('created')}</th><th>{t('action')}</th></tr></thead><tbody>{load.data.map(report=><Fragment key={report.id}><tr><td><strong>{['support','project','mentor','message','booking'].includes(report.entity_type)?supportText(locale,report.entity_type as SupportPhrase):label(report.entity_type)}</strong>{report.entity_type!=='support'&&<small className="word-break">{report.entity_id}</small>}</td><td className="word-break">{report.reporter_id}</td><td className="pre-line">{report.reason}</td><td><Badge tone={report.status==='resolved'?'success':'warning'}>{supportText(locale,reportStatus(report.status))}</Badge></td><td>{dateTime(report.created_at,locale)}</td><td><Button variant="secondary" onClick={()=>setSelected(selected===report.id?'':report.id)}>{supportText(locale,selected===report.id?'close':'view')}</Button></td></tr>{selected===report.id&&<tr><td colSpan={6}><div className="stack"><ReportConversation report={report} refresh={load.reload}/><ReportReview report={report} refresh={load.reload}/></div></td></tr>}</Fragment>)}</tbody></table></div>:<NoData/>}<Pager {...load} hasNext={load.data?.length===25}/></DataState>;}
export default function Page(){return <AdminShell title="reports" description="moderationNote"><Reports/></AdminShell>;}
