export const publicContent = {
  ru: {
    name: "Менторская платформа Women in Tech Kazakhstan",
    headline: "Превращайте идеи в реальные проекты вместе с менторами",
    description: "Найдите ментора, присоединитесь к проекту или предложите собственную идею. Women in Tech Kazakhstan объединяет участников и экспертов и помогает достигать измеримых результатов.",
    findMentor: "Найти ментора", projects: "Смотреть проекты", mentors: "Менторы", participants: "Участники", projectsLabel: "Проекты",
    statsTitle: "Наше сообщество в цифрах", statsNote: "Участники — одобренные менторы и менти с заполненными анкетами и актуальными согласиями. Менторы входят в число участников. Проекты включают опубликованные идеи, доступные в каталоге.",
    statsError: "Не удалось загрузить показатели.", demoStats: "Демонстрационные данные", retry: "Повторить", loading: "Загружаем показатели…",
    connection: "Идея · Поддержка · Результат", idea: "Ваша идея", support: "Поддержка ментора", result: "Реальный проект",
    about: "О платформе", community: "Сообщество", join: "Присоединиться", aboutIntro: "Пространство, где идея получает поддержку и становится проектом.",
    aboutText: "На платформе можно найти ментора по направлению, обсудить цель, присоединиться к проекту или предложить собственную идею. Участники договариваются о формате работы и фиксируют результат совместного пути.",
    rolesTitle: "Два способа начать", mentee: "Для менти", menteeText: "Сформулируйте цель, заполните анкету и выберите направление. После проверки анкеты можно подать заявку ментору или присоединиться к доступному проекту.", mentor: "Для менторов", mentorText: "Расскажите об опыте, направлениях и доступных местах. После проверки анкеты вы сможете рассматривать заявки и помогать участникам двигаться к согласованной цели.",
    menteeAction: "Стать менти", mentorAction: "Стать ментором", pathTitle: "Как устроено участие", steps: ["Выберите роль и заполните анкету", "Ознакомьтесь с документами и пройдите проверку", "Найдите ментора или проект и согласуйте цель", "Проводите встречи и фиксируйте результат"],
    communityIntro: "Знакомьтесь, обменивайтесь опытом и создавайте вместе.", communityText: "Начните с темы, которая вам интересна: найдите эксперта, изучите открытые проекты или предложите идею. Совместная работа начинается с понятной цели и договорённости об участии.",
    communityCards: [
      { title: "Найдите поддержку", text: "Изучите направления и опыт менторов. Выберите человека, чья экспертиза поможет вашей цели.", action: "Перейти к менторам", href: "/catalog" },
      { title: "Присоединитесь к проекту", text: "Посмотрите опубликованные проекты и идеи. На странице проекта можно узнать детали и доступные способы участия.", action: "Посмотреть проекты", href: "/projects" },
      { title: "Предложите идею", text: "Создайте учётную запись и заполните анкету. После проверки участнику доступна публикация собственной идеи.", action: "Начать участие", href: "/register" },
    ],
    resultsTitle: "Делитесь тем, что получилось", resultsText: "Завершённая работа — основа следующего шага. В витрине можно познакомиться с опубликованными результатами участников.", resultsAction: "Посмотреть результаты",
  },
  kk: {
    name: "Women in Tech Kazakhstan менторлық платформасы",
    headline: "Идеяларды менторлармен бірге нақты жобаларға айналдырыңыз",
    description: "Ментор табыңыз, жобаға қосылыңыз немесе өз идеяңызды ұсыныңыз. Women in Tech Kazakhstan қатысушылар мен сарапшыларды біріктіріп, өлшенетін нәтижелерге қол жеткізуге көмектеседі.",
    findMentor: "Ментор табу", projects: "Жобаларды көру", mentors: "Менторлар", participants: "Қатысушылар", projectsLabel: "Жобалар",
    statsTitle: "Қауымдастық сандармен", statsNote: "Қатысушылар — сауалнамаларын толтырып, қолданыстағы келісімдерді қабылдаған, мақұлданған менторлар мен ментилер. Менторлар қатысушылар санына кіреді. Жобалар санына каталогтағы жарияланған идеялар да кіреді.",
    statsError: "Көрсеткіштерді жүктеу мүмкін болмады.", demoStats: "Демонстрациялық деректер", retry: "Қайталау", loading: "Көрсеткіштер жүктелуде…",
    connection: "Идея · Қолдау · Нәтиже", idea: "Сіздің идеяңыз", support: "Ментордың қолдауы", result: "Нақты жоба",
    about: "Платформа туралы", community: "Қауымдастық", join: "Қосылу", aboutIntro: "Идея қолдау тауып, жобаға айналатын орта.",
    aboutText: "Платформада өз бағытыңыз бойынша ментор тауып, мақсатты талқылауға, жобаға қосылуға немесе өз идеяңызды ұсынуға болады. Қатысушылар жұмыс форматын келісіп, бірлескен жұмыстың нәтижесін тіркейді.",
    rolesTitle: "Бастаудың екі жолы", mentee: "Менти үшін", menteeText: "Мақсатыңызды анықтап, сауалнаманы толтырыңыз және бағыт таңдаңыз. Сауалнама тексерілгеннен кейін менторға өтінім беруге немесе қолжетімді жобаға қосылуға болады.", mentor: "Менторлар үшін", mentorText: "Тәжірибеңіз, бағыттарыңыз және бос орындар туралы жазыңыз. Сауалнама тексерілгеннен кейін өтінімдерді қарап, қатысушыларға келісілген мақсатқа жетуге көмектесе аласыз.",
    menteeAction: "Менти болу", mentorAction: "Ментор болу", pathTitle: "Қатысу тәртібі", steps: ["Рөлді таңдап, сауалнаманы толтырыңыз", "Құжаттармен танысып, тексеруден өтіңіз", "Ментор немесе жоба тауып, мақсатты келісіңіз", "Кездесулер өткізіп, нәтижені тіркеңіз"],
    communityIntro: "Танысыңыз, тәжірибе алмасыңыз және бірге жасаңыз.", communityText: "Өзіңізге қызықты тақырыптан бастаңыз: сарапшы табыңыз, ашық жобаларды зерттеңіз немесе идея ұсыныңыз. Бірлескен жұмыс нақты мақсат пен қатысу туралы келісімнен басталады.",
    communityCards: [
      { title: "Қолдау табыңыз", text: "Менторлардың бағыттары мен тәжірибесін қараңыз. Мақсатыңызға жетуге көмектесетін маманды таңдаңыз.", action: "Менторларды көру", href: "/catalog" },
      { title: "Жобаға қосылыңыз", text: "Жарияланған жобалар мен идеяларды қараңыз. Жоба бетінде толық ақпарат пен қатысу жолдары көрсетілген.", action: "Жобаларды көру", href: "/projects" },
      { title: "Идея ұсыныңыз", text: "Тіркеліп, сауалнаманы толтырыңыз. Тексеруден кейін қатысушы өз идеясын жариялай алады.", action: "Қатысуды бастау", href: "/register" },
    ],
    resultsTitle: "Нәтижеңізбен бөлісіңіз", resultsText: "Аяқталған жұмыс — келесі қадамның негізі. Витринада қатысушылардың жарияланған нәтижелерімен танысуға болады.", resultsAction: "Нәтижелерді көру",
  },
  en: {
    name: "Women in Tech Kazakhstan Mentoring Platform",
    headline: "Turn Ideas into Real Projects with the support of Mentors",
    description: "Find a mentor, join a project or share your own idea. Women in Tech Kazakhstan connects participants and experts and helps them achieve measurable results.",
    findMentor: "Find a Mentor", projects: "Explore Projects", mentors: "Mentors", participants: "Participants", projectsLabel: "Projects",
    statsTitle: "Our community in numbers", statsNote: "Participants are approved mentors and mentees with completed profiles and current consents. Mentors are included in participants. Projects include published ideas available in the catalogue.",
    statsError: "The numbers could not be loaded.", demoStats: "Demonstration data", retry: "Try again", loading: "Loading numbers…",
    connection: "Idea · Support · Result", idea: "Your idea", support: "Mentor support", result: "A real project",
    about: "About", community: "Community", join: "Join", aboutIntro: "A place where an idea finds support and becomes a project.",
    aboutText: "Find a mentor in your field, discuss a goal, join a project or share an idea. Participants agree on how to work together and record the outcome of their shared journey.",
    rolesTitle: "Two ways to begin", mentee: "For mentees", menteeText: "Define your goal, complete your profile and choose a field. Once your profile is approved, you can apply to a mentor or join an available project.", mentor: "For mentors", mentorText: "Share your experience, fields and available places. Once your profile is approved, you can review applications and help participants work towards an agreed goal.",
    menteeAction: "Become a mentee", mentorAction: "Become a mentor", pathTitle: "How participation works", steps: ["Choose a role and complete your profile", "Read the documents and complete the review", "Find a mentor or project and agree on a goal", "Meet regularly and record your result"],
    communityIntro: "Connect, exchange experience and create together.", communityText: "Start with a topic you care about: find an expert, explore open projects or propose an idea. Shared work starts with a clear goal and an agreement on participation.",
    communityCards: [
      { title: "Find support", text: "Explore mentors’ fields and experience. Choose someone whose expertise can help you reach your goal.", action: "Explore mentors", href: "/catalog" },
      { title: "Join a project", text: "Browse published projects and ideas. Each project page explains the details and available ways to participate.", action: "Explore projects", href: "/projects" },
      { title: "Share an idea", text: "Create an account and complete your profile. Approved participants can publish their own ideas.", action: "Get started", href: "/register" },
    ],
    resultsTitle: "Share what you achieved", resultsText: "Completed work is the starting point for your next step. Explore participants’ published outcomes in the showcase.", resultsAction: "Explore results",
  },
};
